version: '3.8'
services:
  server:
    build:
      dockerfile: cmd/server/Dockerfile
      context: ./
    ports:
      - "8888:8888"
    networks:
      - appnet
  client:
    build:
      dockerfile: cmd/client/Dockerfile
      context: ./
    networks:
      - appnet

networks:
  appnet:
    driver: bridge